mywheelchair: # namespace
  # publish all joint states
  joint_state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50
     joints:
        - left_wheel_hinge
        - right_wheel_hinge
        - seat_back_hinge

  # drive controllers
  mobile_base_controller:
     type: "diff_drive_controller/DiffDriveController"
     left_wheel: 'left_wheel_hinge'
     right_wheel: 'right_wheel_hinge'
     pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
     twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # position controllers
  joint_seatback_position_controller:
     type: effort_controllers/JointPositionController
     joint: seat_back_hinge
     pid: {p: 100.0, i: 0.01, d: 10.0}


